# General {{{1
title: História da Arquitetura e da Arte II
author: Pedro P. Palazzo
email: palazzo@unb.br
description: >-
  História das cidades, dos edifícios e da edificação na tradição
  europeia a partir do início do Renascimento na Itália até o século
  XVIII. Transposição da tradição técnico-construtiva e arquitetônica da
  Europa para as colônias americanas de fala inglesa e francesa.
baseurl: "/tau0006"
url: "https://palazzo.arq.br"
lang: pt-BR
include_before: |
  <div class="site-title">
    <img src="https://repository-images.githubusercontent.com/277311883/0b465300-64d2-11eb-9ef5-97c6d5e4ca1c" />
  </div>

# Content {{{1
collections:
  aula:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

# Build settings {{{1
# Theme {{{2
theme: tufte-pandoc-jekyll
header_pages:
  - plano.md
  - cronograma.md
minima:
  date_format : "%e %B %Y"
  social_links:
    twitter   : p3palazzo
    github    : p3palazzo
    instagram : arqtrad

# Build parameters {{{2
markdown: Pandoc
pandoc:
  extensions:
    - defaults: "_spec/html.yaml"
    - section-divs
readme_index:
  enabled         : true
  remove_originals: true
  with_frontmatter: true
relative_links:
  enabled         : true
  collections     : true
sass_dir:
  load_paths:
    - _sass
    - assets
    - assets/css
    - assets/css-slides
    - reveal.js/css/theme/template
timezone: America/Sao_Paulo

# Plugins {{{2
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  #- kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links

# Keep and Exclude {{{2
exclude:
  - LICENSE
  - Makefile
  - reveal.js
  - "*.aux"
  - "*.bbl"
  - "*.bcf"
  - "*.bib"
  - "*.blg"
  - "*.fdb_latexmk"
  - "*.fls"
  - "*.log"
  - "*.run.xml"
  - "*.fdb_latexmk"
  - "*.run.xml"
include:
  - README.md
keep_files:
  - .git
  - reveal.js
  - slides
# vim: set foldmethod=marker :
