name: Website
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build the website
      run: make
    - name: Upload site
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: '_site/*'
  commit:
    runs-on: ubuntu-latest
    needs: [ jekyll ]
    if: github.event_name == 'push' && github.repository == 'p3palazzo/tau0006'
    env:
      commit_message: ${{ github.event.head_commit.message }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
    - name: Clear previous site
      run: |
        cd ${{ github.workspace }} && rm -r *
    - name: Download site
      uses: actions/download-artifact@v2
      with:
        name: site
        path: ${{ github.workspace }}/
    - name: Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}
        git config --local user.email "runner@github.com"
        git config --local user.name  "Automated build"
        git add .
        git commit -m "${{ env.commit_message }}" -a || git status
        git pull --rebase
        git push
