name: PDF
on:
  #pull_request:
  #push:
    #branches: [ master ]
jobs:
  plano:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make tau0006-plano.tex
    - run: make tau0006-plano.pdf
  cronograma:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make tau0006-cronograma.pdf
