name: PDF
on:
  #pull_request:
  #push:
    #branches: [ master ]
jobs:
  plano:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make plano.pdf
  cronograma:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make cronograma.pdf
